plugins {
    id("java")
    id("com.github.johnrengelman.shadow").version("8.1.1")
}

allprojects {
    apply(plugin: "java")
    apply(plugin: "com.github.johnrengelman.shadow")

    configurations {
        register("shade") {
            compileOnly.extendsFrom(it)
        }

        register("shadeOnly")
    }

    repositories {
        mavenCentral()

        maven {
            name = "JitPack"
            url = "https://jitpack.io"
        }
        maven {
            name = "Exceptionflug"
            url = "https://mvn.exceptionflug.de/repository/exceptionflug-public"
        }
        maven {
            name = "PaperMC"
            url = "https://repo.papermc.io/repository/maven-public"
        }
    }

    dependencies {
        annotationProcessor("org.projectlombok:lombok:${project.lombok_version}")
        compileOnly("org.projectlombok:lombok:${project.lombok_version}")
        compileOnly("dev.simplix:protocolize-api:${project.protocolize_version}")
        compileOnly("com.github.simplix-softworks:simplixstorage:${project.simplixstorage_version}")
        shadeOnly("com.github.simplix-softworks:simplixstorage:${project.simplixstorage_version}") {
            transitive = false
        }
    }

    def ENV = System.getenv()
    String realVersion = "${project.plugin_version}"

    realVersion += "." + (ENV.BUILD_NUMBER ? "${ENV.BUILD_NUMBER}" : Integer.MAX_VALUE)
    realVersion += ENV.COMMIT_SHA ? "+${ENV.COMMIT_SHA}" : ""
    switch (ENV.BUILD_TYPE) {
        case "RELEASE":
            realVersion += "-stable"
            break
        case "BETA":
            realVersion += "-beta"
            break
        default:
            realVersion += "-dev"
    }



    base {
        if (project.name != rootProject.name) {
            archivesName = "${rootProject.name}${project.name.replace("${project.plugin_name}".toLowerCase(), "")}"
        }

        version = realVersion
        group = project.maven_group
        description = project.plugin_description
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8

        withSourcesJar()
    }

    assemble {
        dependsOn("shadowJar")
    }

    shadowJar {
        dependsOn(jar)
        from("LICENSE")

        configurations.clear()
        configurations.add(project.configurations.shade)
        configurations.add(project.configurations.shadeOnly)

        exclude("META-INF/maven/**/*", "META-INF/*.txt")
        relocate("de.leonhard.storage", "${project.maven_group.replaceAll("-", "")}.lib.de.leonhard.storage")

        // Remove '-all' suffix
        archiveClassifier = null
    }
}

shadowJar {
    dependsOn(project.subprojects.collect {
        // Possible solution, it works.
        it.name == "autoworldmap-common" ? it.tasks.jar : it.tasks.shadowJar
    })

    doFirst {
        // Clean up legacy files.
        delete fileTree("build/tmp/merged")

        copy {
            from {
                project.subprojects.collect {
                    "${it.projectDir}/build/classes/java/main"
                }
            }

            from {
                project.subprojects.collect {
                    "${it.projectDir}/build/resources/main"
                }
            }

            into("build/tmp/merged")
        }
    }

    from("build/tmp/merged")
}
